### ISSUE TITLE
Latest version on npm is es6?

### ISSUE THREAD

**Issue by chris-heathwood-mood** [d3plus/d3plus-common#100]
Hi,

Thanks for all of the work on this, we're having a slight issue with 0.6.50.

The latest release of d3plus-common (0.6.50) has not been babelified (or whatever you are using to make it es5 compatible?).

https://registry.npmjs.org/d3plus-common/-/d3plus-common-0.6.50.tgz

Version 0.6.49 was.

https://registry.npmjs.org/d3plus-common/-/d3plus-common-0.6.49.tgz

If you unzip them both you can see the difference.

We have pinned to 0.6.49 for now but just to let you know :)

**Comment by davelandry** [comment]
@chris-heathwood-mood thanks for reporting this. Totally an oversight on my part (we switched from buble to babel, and something must have broke here). I'm working on a fix right now.

**Comment by davelandry** [comment]
@chris-heathwood-mood just pushed the fix with `v0.6.51`. Let me know if that doesn't work for you!

Also, out of curiosity, which parts of d3plus-common are you using? I always love hearing use cases 😄

**Comment by chris-heathwood-mood** [comment]
@davelandry Thanks for the quick fix will test this and will let you know if we have any issues :)

It is used by d3plus-text which we use to do some text wrapping in SVG all over the place so thanks 👍
