### ISSUE TITLE
ES5 compatibility in latest version

### ISSUE THREAD

**Issue by cheryllaird** [d3plus/d3plus-common#101]
We updated to version `0.6.53` and noticed that the new dependency of `locale-codes` is ES6. 
This is causing problems similar to https://github.com/d3plus/d3plus-common/issues/100 with ES5 compatibility.

Not a problem as we have pinned to an older version but wanted to make you aware.

Many thanks :)

**Comment by davelandry** [comment]
Ahhh yikes, good catch. We're only using a very small part of that library, so it should be easy for us to fix this.

**Comment by cheryllaird** [comment]
Oh that is great news, I will look out for the update. Thank you for your work on this.

**Comment by davelandry** [comment]
@cheryllaird I just released v0.6.54 with a fix, let me know if that doesn't work for you!

**Comment by cheryllaird** [comment]
Great, we are now on the latest version and all looks good. Thanks.
