### ISSUE TITLE
create global localization object

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-common#85]
Localization is something that we've supported in the past that has not been properly addressed in the new version of d3plus. D3 contains some great [time formatters](https://github.com/d3/d3-time-format/tree/master/locale), so let's implement a solution that combines any built-ins we can find with more specific word localizations (like the text for the "back" button).

My current idea is to have a global `locale` object exported by this module, and that object would contain keys for each language, which then in turn contain keys for specific types of localizations. An example format is here:

```js
export default {
  "en-US": {
    time: {...}, // object imported from d3-time-format
    text: {
      back: "Back",
      ...
    }
  },
  "es-ES": {
    time: {...}, // object imported from d3-time-format
    text: {
      back: "Volver",
      ...
    }
  }
}
```

This object would be created in `src/locale/index.js`, importing all of the d3-time-format language modules, and importing our own modules from files like `src/locale/text/es-ES.js`. We would then add a `.locale("es-ES")` method to `BaseClass` so that every component can support localization.

@cnavarreteliz, @nbond211, thoughts?

**Comment by cnavarreteliz** [comment]
can I close this issue @davelandry ?
